# Werkcollege-opdrachten Week 1.3

## Dependencies importeren

Kopieer in het codeblok hieronder van het vorige werkcollege de import-code voor de dependencies die het vaakst worden gebruikt om data in te lezen. Geef er ook de gebruikelijke aliassen aan.<br>
Zet eventuele warnings uit.

In [1]:
import pandas as pd
import sqlite3
import warnings
warnings.simplefilter('ignore')

Zet de volgende bestanden in een makkelijk te vinden map, als je dat nog niet gedaan hebt:
- go_sales.sqlite
- go_crm.sqlite
- go_staff.sqlite

## Databasetabellen inlezen

Kopieer in het codeblok hieronder van het vorige werkcollege de code om een connectie met het bestand go_sales.sqlite te maken.

In [2]:
import sqlite3
connectie = sqlite3.connect('go_sales.sqlite')
print("database import gelukt!")

database import gelukt!

Lees van de ingelezen go_sales-database te volgende tabellen in met behulp van "SELECT * FROM *tabel*".
- product
- product_type
- product_line
- sales_staff
- sales_branch
- retailer_site
- country
- order_header
- order_details
- returned_item
- return_reason

In [9]:
import pandas as pd



product_df = pd.read_sql_query("SELECT * FROM product", connectie)
product_type_df = pd.read_sql_query("SELECT * FROM product_type", connectie)
product_line_df = pd.read_sql_query("SELECT * FROM product_line", connectie)
sales_staff_df = pd.read_sql_query("SELECT * FROM sales_staff", connectie)
sales_branch_df = pd.read_sql_query("SELECT * FROM sales_branch", connectie)
retailer_site_df = pd.read_sql_query("SELECT * FROM retailer_site", connectie)
country_df = pd.read_sql_query("SELECT * FROM country", connectie)
order_header_df = pd.read_sql_query("SELECT * FROM order_header", connectie)
order_details_df = pd.read_sql_query("SELECT * FROM order_details", connectie)
returned_item_df = pd.read_sql_query("SELECT * FROM returned_item", connectie)
return_reason_df = pd.read_sql_query("SELECT * FROM return_reason", connectie)

print ("tabel import gelukt")

tabel import gelukt

Krijg je een "no such table" error? Dan heb je misschien met .connect() per ongeluk een leeg  databasebestand (.sqlite) aangemaakt.<br> <u>Let op:</u> lees eventueel de informatie uit het vorige werkcollege nog eens goed door.

Als je tijdens onderstaande opdrachten uit het oog verliest welke tabellen er allemaal zijn, kan je deze Pythoncode uitvoeren:

In [10]:
sql_query = "SELECT * FROM sqlite_master WHERE type='table';"
#Vul dit codeblok verder in
pd.read_sql(sql_query, connectie)
#Op de puntjes hoort de connectie naar go_sales óf go_staff óf go_crm te staan.

,type,name,tbl_name,rootpage,sql
0,table,country,country,480,"CREATE TABLE ""country"" (\n\t""COUNTRY_CODE""\tIN..."
1,table,order_details,order_details,11,"CREATE TABLE ""order_details"" (\n\t""ORDER_DETAI..."
2,table,order_header,order_header,24,"CREATE TABLE ""order_header"" (\n\t""ORDER_NUMBER..."
3,table,order_method,order_method,27,"CREATE TABLE ""order_method"" (\n\t""ORDER_METHOD..."
4,table,product,product,28,"CREATE TABLE ""product"" (\n\t""PRODUCT_NUMBER""\t..."
5,table,product_line,product_line,17,"CREATE TABLE ""product_line"" (\n\t""PRODUCT_LINE..."
6,table,product_type,product_type,10,"CREATE TABLE ""product_type"" (\n\t""PRODUCT_TYPE..."
7,table,retailer_site,retailer_site,18,"CREATE TABLE ""retailer_site"" (\n\t""RETAILER_SI..."
8,table,return_reason,return_reason,30,"CREATE TABLE ""return_reason"" (\n\t""RETURN_REAS..."
9,table,returned_item,returned_item,31,"CREATE TABLE ""returned_item"" (\n\t""RETURN_CODE..."
10,table,sales_branch,sales_branch,2,"CREATE TABLE ""sales_branch"" (\n\t""SALES_BRANCH..."
11,table,sales_staff,sales_staff,3,"CREATE TABLE ""sales_staff"" (\n\t""SALES_STAFF_C..."

Let op! Voor alle onderstaande opdrachten mag je <u>alleen Python</u> gebruiken, <u>geen SQL!</u>

## Selecties op één tabel zonder functies

Geef een overzicht met daarin de producten en hun productiekosten waarvan de productiekosten lager dan 100 dollar en hoger dan 50 dollar ligt. (2 kolommen, 23 rijen)

In [12]:

q1_df = product_df.loc[ 
    (product_df['PRODUCTION_COST'] > 50) & (product_df['PRODUCTION_COST'] < 100),
    ['PRODUCT_NAME', 'PRODUCTION_COST'] 
]
print(q1_df)

                        PRODUCT_NAME  PRODUCTION_COST
5          TrailChef Deluxe Cook Set            85.11
7             TrailChef Double Flame            75.00
16                   Hibernator Lite            60.00
17                        Hibernator            86.00
19   Hibernator Self - Inflating Mat            78.55
22               Hibernator Camp Cot            65.33
23      Canyon Mule Climber Backpack            62.50
45           Granite Climbing Helmet            52.86
47             Husky Harness Extreme            55.00
57                    Granite Hammer            57.13
68                         Polar Ice            73.33
69                      Polar Sports            80.00
70                        Polar Wave            60.00
71                     Polar Extreme            72.50
74                      Edge Extreme            80.00
77                         Seeker 35            79.19
78                         Seeker 50            92.58
79                    Seeker Extreme            94.12
82                    Glacier Deluxe            56.25
83                       Glacier GPS            78.55
109                Blue Steel Putter            60.00
110            Blue Steel Max Putter            81.80
113              Course Pro Golf Bag            80.00

Geef een overzicht met daarin de producten en hun marge waarvan de marge lager dan 20 % of hoger dan 60 % ligt. (2 kolommen, 7 rijen)

In [14]:
q2_df = product_df.loc[ 
    (product_df['MARGIN'] < 0.20) | (product_df['MARGIN'] > 0.60),
    ['PRODUCT_NAME', 'MARGIN']
]
print(q2_df)

                    PRODUCT_NAME  MARGIN
20                Hibernator Pad    0.17
23  Canyon Mule Climber Backpack    0.17
85             BugShield Natural    0.67
86               BugShield Spray    0.67
87         BugShield Lotion Lite    0.70
88              BugShield Lotion    0.63
89             BugShield Extreme    0.63

Geef een overzicht met daarin de landen waar met francs wordt betaald. Sorteer de uitkomst op land.  (1 kolom, 3 rijen)

In [26]:
q3_df = country_df.loc[ 
    (country_df['CURRENCY_NAME'].str.contains('francs')),
    ['COUNTRY']
].sort_values('COUNTRY')
print(q3_df)

        COUNTRY
15      Belgium
0        France
7   Switzerland

Geef een overzicht met daarin de verschillende introductiedatums waarop producten met meer dan 50% marge worden geïntroduceerd (1 kolom, 7 rijen)

In [39]:
q4_df = product_df.loc[ 
    (product_df['MARGIN'] > 0.50),
    ['INTRODUCTION_DATE'] 
].drop_duplicates()
print(q4_df)

    INTRODUCTION_DATE
66         2000-10-26
85         1995-02-15
101        2003-12-10
103        2003-12-18
104        2003-12-27
106        2004-01-13
110        2003-12-15

Geef een overzicht met daarin het eerste adres en de stad van verkoopafdelingen waarvan zowel het tweede adres als de regio bekend is (2 kolommen, 7 rijen)

In [ ]:
q5_df = sales_branch_df.loc[ 
    (sales_branch_df['ADDRESS2'].notna()) & (sales_branch_df['REGION'].notna()),
    ['ADDRESS1', 'CITY']
]
print(q5_df)

                            ADDRESS1              CITY
2                Singelgravenplein 4         Amsterdam
13  Prol. Paseo de la Reforma No. 51  Distrito Federal
14               202-2-3 Hyakunincho             Tokyo
15                     543-225 Asahi        Osaka City
16                  2315 Queen's Ave         Melbourne
18             Avenida Paulista, 333         São Paulo
24                    3 Albany Court        Birmingham

Geef een overzicht met daarin de landen waar met dollars (dollars of new dollar) wordt betaald. Sorteer de uitkomst op land. (1 kolom, 4 rijen)

In [52]:
q6_df = country_df.loc[ 
    (country_df['CURRENCY_NAME'].str.contains('dollars')) | (country_df['CURRENCY_NAME'].str.contains('new dollar')),
    ['COUNTRY'] 
].drop_duplicates()
print(q6_df)

          COUNTRY
2   United States
3          Canada
11         Taiwan
14      Australia

In [57]:
retailer_site_df.head(20)

,RETAILER_SITE_CODE,RETAILER_CODE,ADDRESS1,ADDRESS2,CITY,REGION,POSTAL_ZONE,COUNTRY_CODE,ACTIVE_INDICATOR
0,1,89,1117 Franklin Blvd,NaN,Winnipeg,Manitoba,R2C 0M5,4,1
1,2,89,"45, rue Atwater",NaN,Montréal,Québec,H2T 9K8,4,1
2,3,89,328 Hodgson Road,NaN,Fredericton,New Brunswick,E3B 2H2,4,1
3,4,90,"2425, rue Peel",NaN,Montréal,Québec,H4G 3T4,4,1
4,5,90,34 8th Avenue,NaN,Sudbury,Ontario,M5V 1G5,4,1
5,6,90,"45, rue Stanley",NaN,Tremblant,Québec,H5Y 2S9,4,1
6,7,90,23 Louis Riel Drive,NaN,Regina,Saskatchewan,S1J 3C5,4,1
7,8,91,56 North Way Street,NaN,Whitehorse,Yukon,Y2K 6R0,4,1
8,9,92,601 Bay Street,NaN,Toronto,Ontario,M2M 7K8,4,1
9,10,92,"Suite 1500, 802 Docklands Street",NaN,Vancouver,British Columbia,V6E 3Z3,4,1
10,11,92,"Suite 125, 129th Street",NaN,Vancouver,British Columbia,V1E 4R6,4,1
11,12,92,"Suite 5034, 34 Broadway Street",NaN,Vancouver,British Columbia,V5R 1W3,4,1
12,13,92,"18, rue Rousseau",NaN,Montréal,Québec,H2T 2J6,4,1
13,14,93,"500, Place d'Armes",Bureau 1061,Montréal,Québec,H2Y 2W2,4,1
14,15,94,82 Creekside Drive,NaN,Victoria,British Columbia,V10 6T5,4,1
15,16,94,"48, rue Leduc",NaN,Hull,Québec,J8Y 3Z5,4,0
16,17,95,"203, boul. Guy",NaN,Montréal,Québec,H3T 8L4,4,1
17,18,95,"603, 42 Bloor St.",NaN,Toronto,Ontario,M1R 4K3,4,1
18,19,95,9755 Riverside Drive,NaN,Ottawa,Ontario,K1G 4Z0,4,1
19,20,95,2200 Argyle Street,NaN,Halifax,Nova Scotia,B3J 9S2,4,1

Geef een overzicht met daarin beide adressen en de stad van vestigingen van klanten waarvan de postcode begint met een ‘D’ (van duitsland). Filter op vestigingen die een tweede adres hebben. (3 kolommen, 2 rijen)

In [58]:
q7_df = retailer_site_df.loc[
    (retailer_site_df['POSTAL_ZONE'].str.startswith('D')) & (retailer_site_df['ADDRESS2'].notna()),
    ['ADDRESS1', 'ADDRESS2', 'CITY']
]
print(q7_df)

            ADDRESS1       ADDRESS2       CITY
31  Röntgenstraße 90  3. Tür rechts  Frankfurt
59   Grubesallee 141       4. Stock    Hamburg

## Selecties op één tabel met functies

Geef het totaal aantal producten dat is teruggebracht (1 waarde)

In [ ]:
# Totaal aantal producten dat is teruggebracht
totaal_terug = returned_item_df['RETURN_CODE'].count() BURDA KALDIM
print(totaal_terug)

619

Geef het aantal regio’s waarin verkoopafdelingen gevestigd zijn. (1 waarde)

In [25]:
# Aantal unieke regio's
aantal_regios = sales_branch_df['REGION'].nunique()
print(aantal_regios)

15

Maak 3 variabelen:
- Een met de laagste
- Een met de hoogste
- Een met de gemiddelde (afgerond op 2 decimalen)

marge van producten (3 kolommen, 1 rij)

In [26]:
# Bereken de variabelen
laagste = product_df['MARGIN'].min()
hoogste = product_df['MARGIN'].max()
gemiddelde = round(product_df['MARGIN'].mean(), 2)

# Stop ze in een DataFrame (3 kolommen, 1 rij)
marge_df = pd.DataFrame({
    'Laagste': [laagste], 
    'Hoogste': [hoogste], 
    'Gemiddelde': [gemiddelde]
})
print(marge_df)

   Laagste  Hoogste  Gemiddelde
0     0.17      0.7         0.4

Geef het aantal vestigingen van klanten waarvan het 2e adres niet bekend is (1 waarde)

In [27]:
# Aantal vestigingen waar ADDRESS2 leeg (NaN) is
onbekend_adres2 = retailer_site_df['ADDRESS2'].isna().sum()
print(onbekend_adres2)

286

Geef de gemiddelde kostprijs van de verkochte producten waarop korting (unit_sale_price < unit_price) is verleend (1 waarde)

In [28]:
# Eerst filteren met .loc en direct de UNIT_COST kolom pakken
korting_items = order_details_df.loc[
    order_details_df['UNIT_SALE_PRICE'] < order_details_df['UNIT_PRICE'], 
    'UNIT_COST'
]

gemiddelde_kostprijs = korting_items.mean()
print(gemiddelde_kostprijs)

127.34087927598803

Geef een overzicht met daarin het aantal medewerkers per medewerkersfunctie (2 kolommen, 7 rijen)

In [29]:
# Groeperen per functie en medewerkers tellen (zoals op slide 87)
functie_telling = sales_staff_df.groupby('POSITION_EN', as_index=False)['SALES_STAFF_CODE'].count()
print(functie_telling)

                    POSITION_EN  SALES_STAFF_CODE
0                Branch Manager                19
1              District Manager                 4
2               General Manager                 1
3  Level 1 Sales Representative                13
4  Level 2 Sales Representative                39
5  Level 3 Sales Representative                24
6              Regional Manager                 2

Geef een overzicht met daarin per telefoonnummer het aantal medewerkers dat op dat telefoonnummer bereikbaar is. Toon alleen de telefoonnummer waarop meer dan 4 medewerkers bereikbaar zijn. (2 kolommen, 10 rijen)

In [30]:
# Stap 1: Tel het aantal medewerkers per telefoonnummer
telefoon_telling = sales_staff_df.groupby('WORK_PHONE', as_index=False)['SALES_STAFF_CODE'].count()

# Stap 2: Filter met .loc op nummers met meer dan 4 medewerkers
veel_gebruikt = telefoon_telling.loc[telefoon_telling['SALES_STAFF_CODE'] > 4, :]
print(veel_gebruikt)

             WORK_PHONE  SALES_STAFF_CODE
4     +(44) 121 3505267                 5
10  +(61) 03 2982  4242                 5
11  +31 (0)20 692 93 94                 5
13    +33 1 68 94 52 20                 5
18     1 (206) 292-0012                 5
19     1 (305) 557-4810                 6
20     1 (310) 281-5722                 5
21     1 (403) 232-5986                 5
22     1 (416) 493-5595                 5
23     1 (617) 268-6754                 6

## Selecties op meerdere tabellen zonder functies

Geef een overzicht met daarin het eerste adres en de stad van vestigingen van klanten uit ‘Netherlands’ (2 kolommen, 20 rijen)

In [31]:
# 1. Merge de tabellen op basis van de gedeelde kolom (COUNTRY_CODE)
merged_q1 = pd.merge(retailer_site_df, country_df, on='COUNTRY_CODE', how='inner')

# 2. Filter met .loc op 'Netherlands' en selecteer de twee gevraagde kolommen
result_q1 = merged_q1.loc[merged_q1['COUNTRY'] == 'Netherlands', ['ADDRESS1', 'CITY']]

print(result_q1)

                      ADDRESS1          CITY
240                   Beets 36         Beets
241               Perestraat 1      Deventer
242  Laan van Meerdervoort 966      Den Haag
243             Kalfjeslaan 47    Amstelveen
244               Startbaan 11    Amstelveen
245      Noorderspoorsingel 28     Groningen
246              Hogehilweg 13     Amsterdam
247             Spoorstraat 43    Varsseveld
248             Westhavenweg 8     Amsterdam
249              Westzeedijk 4        Muiden
250            Gooiergracht 91         Laren
251            Hoofdstraat 150   Pieterburen
252                Olde Diek 2         Laren
253     Amsterdamsestraatweg 8      Maarssen
254        Krayenhoffstraat 11     Amsterdam
255         Overschiestraat 19     Amsterdam
256              Havenbuurt 12        Marken
257               Duivendaal 1    Wageningen
258              Voorstraat 37  Nieuweschans
259         Stadhouderslaan 18     Rotterdam

Geef een overzicht met daarin de productnamen die tot het producttype ‘Eyewear’ behoren. (1 kolom, 5 rijen)

In [32]:
# 1. Merge product en product_type
merged_q2 = pd.merge(product_df, product_type_df, on='PRODUCT_TYPE_CODE', how='inner')

# 2. Filter op 'Eyewear' en selecteer de productnaam. Gebruik drop_duplicates() voor unieke rijen.
result_q2 = merged_q2.loc[merged_q2['PRODUCT_TYPE_EN'] == 'Eyewear', ['PRODUCT_NAME']].drop_duplicates()

print(result_q2)

     PRODUCT_NAME
67      Polar Sun
68      Polar Ice
69   Polar Sports
70     Polar Wave
71  Polar Extreme

Geef een overzicht met daarin alle unieke eerste adressen van klantvestigingen en de voornaam en achternaam van de verkopers die ‘Branch Manager’ zijn en aan deze vestigingen hebben verkocht (3 kolommen, 1 rij)

In [33]:
# 1. Merge sales_staff, order_header en retailer_site aan elkaar
merge1_q3 = pd.merge(sales_staff_df, order_header_df, on='SALES_STAFF_CODE', how='inner')
merged_q3 = pd.merge(merge1_q3, retailer_site_df, on='RETAILER_SITE_CODE', how='inner')

# 2. Filter op de functie 'Branch Manager' en selecteer de 3 kolommen (uniek)
result_q3 = merged_q3.loc[
    merged_q3['POSITION_EN'] == 'Branch Manager', 
    ['ADDRESS1', 'FIRST_NAME', 'LAST_NAME']
].drop_duplicates()

print(result_q3)

                  ADDRESS1 FIRST_NAME LAST_NAME
3727  Alameda Santos, 9876     Bayard     Lopes

Geef een overzicht met daarin van de verkopers hun functie en indien zij iets hebben verkocht de datum waarop de verkoop heeft plaatsgevonden. Laat alleen de verschillende namen van de posities zien van de verkopers die het woord ‘Manager’ in hun positienaam hebben staan. (2 kolommen, 7 rijen)

In [34]:
# 1. Left merge om alle verkopers te behouden, ook als ze geen order hebben
merged_q4 = pd.merge(sales_staff_df, order_header_df, on='SALES_STAFF_CODE', how='left')

# 2. Filter op medewerkers waarbij het woord 'Manager' in de functietitel staat
voorwaarde_manager = merged_q4['POSITION_EN'].str.contains('Manager')

# 3. Selecteer de functie en de orderdatum, verwijder dubbele rijen
result_q4 = merged_q4.loc[voorwaarde_manager, ['POSITION_EN', 'ORDER_DATE']].drop_duplicates()

print(result_q4)

           POSITION_EN  ORDER_DATE
0       Branch Manager         NaN
320   Regional Manager         NaN
648   District Manager         NaN
3748    Branch Manager  2024-09-09
3749    Branch Manager  2024-03-13
3750    Branch Manager  2024-01-09
4186   General Manager         NaN

Geef een overzicht met daarin de verschillende namen van producten en bijbehorende namen van producttypen van de producten waarvoor ooit meer dan 750 stuks tegelijk verkocht zijn. (2 kolommen, 9 rijen)

In [35]:
# 1. Merge de drie benodigde tabellen
merge1_q5 = pd.merge(product_df, product_type_df, on='PRODUCT_TYPE_CODE', how='inner')
merged_q5 = pd.merge(merge1_q5, order_details_df, on='PRODUCT_NUMBER', how='inner')

# 2. Filter op hoeveelheid > 750 en selecteer de namen (uniek)
result_q5 = merged_q5.loc[
    merged_q5['QUANTITY'] > 750, 
    ['PRODUCT_NAME', 'PRODUCT_TYPE_EN']
].drop_duplicates()

print(result_q5)

                PRODUCT_NAME    PRODUCT_TYPE_EN
5427                Star Peg              Tents
11452              Firefly 2           Lanterns
28608        BugShield Spray  Insect Repellents
28892  BugShield Lotion Lite  Insect Repellents
29430       BugShield Lotion  Insect Repellents
29442      BugShield Extreme  Insect Repellents
30741         Sun Shelter 15          Sunscreen
31164         Sun Shelter 30          Sunscreen
31775             Sun Shield          Sunscreen

Geef een overzicht met daarin de productnamen waarvan ooit meer dan 40% korting is verleend. De formule voor korting is: (unit_price - unit_sale_price) / unit_price (1 kolom, 8 rijen)

In [36]:
# 1. Merge product en order_details
merged_q6 = pd.merge(product_df, order_details_df, on='PRODUCT_NUMBER', how='inner')

# 2. Bereken de kortingsformule: (unit_price - unit_sale_price) / unit_price
korting = (merged_q6['UNIT_PRICE'] - merged_q6['UNIT_SALE_PRICE']) / merged_q6['UNIT_PRICE']

# 3. Filter waar de korting groter is dan 0.40 (40%)
result_q6 = merged_q6.loc[korting > 0.40, ['PRODUCT_NAME']].drop_duplicates()

print(result_q6)

                       PRODUCT_NAME
27830             BugShield Natural
28283               BugShield Spray
28694         BugShield Lotion Lite
29127              BugShield Lotion
29464             BugShield Extreme
30562                Sun Shelter 15
30929                Sun Shelter 30
34441  Hailstorm Titanium Woods Set

Geef een overzicht met daarin de retourreden van producten waarvan ooit meer dan 90% van de aangeschafte hoeveelheid is teruggebracht (return_quantity/quantity). (1 kolom, 3 rijen)

In [37]:
# 1. Merge de drie tabellen
merge1_q7 = pd.merge(returned_item_df, order_details_df, on='ORDER_DETAIL_CODE', how='inner')
merged_q7 = pd.merge(merge1_q7, return_reason_df, on='RETURN_REASON_CODE', how='inner')

# 2. Bereken hoeveel procent is teruggebracht
percentage_retour = merged_q7['RETURN_QUANTITY'] / merged_q7['QUANTITY']

# 3. Filter op > 0.90 (90%) en pak de redenbeschrijving
result_q7 = merged_q7.loc[percentage_retour > 0.90, ['RETURN_DESCRIPTION_EN']].drop_duplicates()

print(result_q7)

    RETURN_DESCRIPTION_EN
0  Unsatisfactory product
2   Wrong product shipped
3   Wrong product ordered

## Selecties op meerdere tabellen met functies

Geef een overzicht met daarin per producttype het aantal producten die tot dat producttype behoren. (2 kolommen, 21 rijen)

In [38]:
# 1. Merge de tabellen product en product_type op basis van de gedeelde code
merged_q1 = pd.merge(product_df, product_type_df, on='PRODUCT_TYPE_CODE', how='inner')

# 2. Groepeer op de naam van het producttype en tel het aantal producten
result_q1 = merged_q1.groupby('PRODUCT_TYPE_EN', as_index=False)['PRODUCT_NUMBER'].count()

print(result_q1)

         PRODUCT_TYPE_EN  PRODUCT_NUMBER
0             Binoculars               4
1   Climbing Accessories               7
2           Cooking Gear              10
3                Eyewear               5
4              First Aid               5
5       Golf Accessories               4
6      Insect Repellents               5
7                  Irons               4
8                 Knives               5
9               Lanterns              12
10            Navigation               4
11                 Packs               6
12               Putters               3
13                  Rope               4
14                Safety               4
15         Sleeping Bags               7
16             Sunscreen               5
17                 Tents               6
18                 Tools               6
19               Watches               5
20                 Woods               4

Geef een overzicht met daarin per land het aantal vestigingen van klanten die zich in dat land bevinden. (2 kolommen, 21 rijen)

In [39]:
# 1. Merge de tabellen retailer_site en country
merged_q2 = pd.merge(retailer_site_df, country_df, on='COUNTRY_CODE', how='inner')

# 2. Groepeer op de landnaam en tel het aantal vestigingen (gebruik RETAILER_SITE_CODE)
result_q2 = merged_q2.groupby('COUNTRY', as_index=False)['RETAILER_SITE_CODE'].count()

print(result_q2)

           COUNTRY  RETAILER_SITE_CODE
0        Australia                  10
1          Austria                  10
2          Belgium                  10
3           Brazil                   1
4           Canada                  31
5            China                  10
6          Denmark                   6
7          Finland                   5
8           France                  29
9          Germany                  32
10           Italy                  12
11           Japan                  25
12           Korea                  10
13          Mexico                  10
14     Netherlands                  20
15           Spain                   9
16          Sweden                  12
17     Switzerland                  13
18          Taiwan                  10
19  United Kingdom                  25
20   United States                 101

Geef een overzicht met daarin van de producten behorend tot het producttype ‘Cooking Gear’ per productnaam de totaal verkochte hoeveelheid en de gemiddelde verkoopprijs. Sorteer de uitkomst op totaal verkochte hoeveelheid. (6 kolommen, 10 rijen)

In [40]:
# 1. Merge de drie benodigde tabellen
merge1_q3 = pd.merge(product_df, product_type_df, on='PRODUCT_TYPE_CODE', how='inner')
merged_q3 = pd.merge(merge1_q3, order_details_df, on='PRODUCT_NUMBER', how='inner')

# 2. Filter met .loc op het producttype 'Cooking Gear'
cooking_gear = merged_q3.loc[merged_q3['PRODUCT_TYPE_EN'] == 'Cooking Gear', :]

# 3. Groepeer op productnaam en gebruik .agg() voor meerdere berekeningen tegelijk
result_q3 = cooking_gear.groupby('PRODUCT_NAME', as_index=False).agg({
    'QUANTITY': 'sum',           # Totaal verkochte hoeveelheid
    'UNIT_SALE_PRICE': 'mean'    # Gemiddelde verkoopprijs
})

# 4. Sorteer de uitkomst op totaal verkochte hoeveelheid
result_q3 = result_q3.sort_values(by='QUANTITY')

print(result_q3)

                PRODUCT_NAME  QUANTITY  UNIT_SALE_PRICE
3  TrailChef Deluxe Cook Set      3110       121.217638
7     TrailChef Single Flame      8504        63.827622
5           TrailChef Kettle      8826        12.201235
1         TrailChef Cook Set     10878        51.687926
4     TrailChef Double Flame     12476       132.672882
8         TrailChef Utensils     13776        17.294151
6      TrailChef Kitchen Kit     22206        22.345975
0          TrailChef Canteen     26544        11.979418
2              TrailChef Cup     27418         6.976490
9        TrailChef Water Bag     36738         6.032506

Geef een overzicht met daarin per land de naam van het land, de naam van de stad waar de verkoopafdeling is gevestigd (noem de kolomnaam in het overzicht ‘verkoper’) en het aantal steden waar zich klanten bevinden in dat land (noem de kolomnaam in het overzicht ‘klanten’) (3 kolommen, 29 rijen)

In [41]:
# 1. Merge sales_branch en country, en hernoem de filiaalstad naar 'verkoper'
branch_country = pd.merge(sales_branch_df, country_df, on='COUNTRY_CODE', how='inner')
branch_country = branch_country.rename(columns={'CITY': 'verkoper'})

# 2. Merge dit resultaat met retailer_site om de klantsteden te krijgen
# De kolom met de klantstad heet nu 'CITY' in dit nieuwe DataFrame
merged_q4 = pd.merge(branch_country, retailer_site_df, on='COUNTRY_CODE', how='inner')

# 3. Groepeer op land en verkoper, en tel de unieke klantsteden (.nunique)
result_q4 = merged_q4.groupby(['COUNTRY', 'verkoper'], as_index=False)['CITY'].nunique()

# 4. Hernoem de laatste kolom naar 'klanten' zoals gevraagd in de opdracht
result_q4 = result_q4.rename(columns={'CITY': 'klanten'})

print(result_q4)

           COUNTRY          verkoper  klanten
0        Australia         Melbourne        6
1          Austria              Wien        9
2          Belgium          Heverlee        8
3           Brazil         São Paulo        1
4           Canada           Calgary       16
5           Canada           Toronto       16
6            China          Shanghai        7
7          Finland            Kuopio        5
8           France              Lyon       14
9           France             Paris       14
10         Germany           Hamburg       18
11         Germany           München       18
12           Italy            Milano        9
13           Japan        Osaka City        5
14           Japan             Tokyo        5
15           Korea             Seoul        6
16          Mexico  Distrito Federal        6
17     Netherlands         Amsterdam       15
18           Spain            Bilbao        5
19          Sweden             Kista       10
20     Switzerland            Zürich        9
21          Taiwan         San Chung        9
22  United Kingdom        Birmingham        9
23  United Kingdom            London        9
24   United States            Boston       62
25   United States       Los Angeles       62
26   United States             Miami       62
27   United States           Seattle       62

## Pythonvertalingen van SUBSELECT en UNION met o.a. for-loops

Geef een overzicht met daarin de voornaam en de achternaam van de medewerkers die nog nooit wat hebben verkocht (2 kolommen, 25 rijen)

In [42]:
# Stap 1: Maak een lijstje (subselect) van alle medewerkers die een order hebben
verkopers_lijst = order_header_df['SALES_STAFF_CODE'].drop_duplicates()

# Stap 2: Gebruik ~ (NOT) en .isin() om medewerkers te vinden die NIET in de lijst staan
nooit_verkocht = sales_staff_df.loc[
    ~sales_staff_df['SALES_STAFF_CODE'].isin(verkopers_lijst), 
    ['FIRST_NAME', 'LAST_NAME']
]

print(nooit_verkocht)

   FIRST_NAME      LAST_NAME
0       Denis           Pagé
5        Else         Mörike
6       Frank          Fuchs
9       Fritz         Hirsch
10       Jörg          Kunze
12      Maria      Iacobucci
17       Kick        Kalkman
22      Karin      Bergström
25      Sally          White
27      Frank        Bretton
28    Georges  Saint-Germain
33       Alex      Rodriguez
37   Samantha          Floyd
41      Julie          Olsen
45      Corey         Wright
51    Estelle        Johnson
52       Greg        Belding
55      Julie        Béchard
59      Lucía          Reyna
64     Kazumi        Uragome
66      Alice         Walter
84     Walter         Taylor
85   Penelope        Tamrine
88      Polly         Linton
96      Gracy        Gellens

Geef een overzicht met daarin het aantal producten waarvan de marge lager is dan de gemiddelde marge van alle producten samen. Geef in het overzicht tevens aan wat de gemiddelde marge is van dit aantal producten waarvan de marge lager dan de gemiddelde marge van alle producten samen is. (1 kolom, 2 rijen)

In [43]:
# 1. Bereken de gemiddelde marge van ALLE producten
gemiddelde_marge_totaal = product_df['MARGIN'].mean()

# 2. Filter producten met een marge LAGER dan dit globale gemiddelde
lage_marge_producten = product_df.loc[product_df['MARGIN'] < gemiddelde_marge_totaal, :]

# 3. Bereken hoeveel dit er zijn, en wat hún specifieke gemiddelde is
aantal_producten = lage_marge_producten['PRODUCT_NUMBER'].count()
gemiddelde_marge_specifiek = lage_marge_producten['MARGIN'].mean()

# 4. Stop dit in een net overzichtje (1 kolom, 2 rijen)
resultaat_marge = pd.DataFrame(
    [aantal_producten, gemiddelde_marge_specifiek],
    columns=['Waarde'],
    index=['Aantal producten', 'Gemiddelde marge van deze groep']
)

print(resultaat_marge)

                                    Waarde
Aantal producten                 59.000000
Gemiddelde marge van deze groep   0.292203

Geef een overzicht met daarin de namen van de producten die voor meer dan 500 (verkoopprijs) zijn verkocht maar nooit zijn teruggebracht. (1 kolom, 13 rijen)

In [44]:
# 1. Filter order_details op verkoopprijs hoger dan 500
dure_orders = order_details_df.loc[order_details_df['UNIT_SALE_PRICE'] > 500, :]

# 2. Maak een lijstje (subselect) van alle codes die geretourneerd zijn
geretourneerd_lijst = returned_item_df['ORDER_DETAIL_CODE'].drop_duplicates()

# 3. Filter dure orders: behoud alleen degene die NIET (~) geretourneerd zijn
nooit_terug_orders = dure_orders.loc[~dure_orders['ORDER_DETAIL_CODE'].isin(geretourneerd_lijst), :]

# 4. Merge met product_df om de naam van het product op te halen
merged_producten = pd.merge(nooit_terug_orders, product_df, on='PRODUCT_NUMBER', how='inner')

# 5. Selecteer de productnamen en verwijder dubbelingen (zodat je 13 unieke rijen krijgt)
resultaat_producten = merged_producten[['PRODUCT_NAME']].drop_duplicates()

print(resultaat_producten)

                          PRODUCT_NAME
0                            Star Dome
6                         Star Gazer 2
14                        Star Gazer 3
23                        Star Gazer 6
31               Hailstorm Steel Irons
40            Hailstorm Titanium Irons
49          Lady Hailstorm Steel Irons
54       Lady Hailstorm Titanium Irons
60        Hailstorm Titanium Woods Set
70           Hailstorm Steel Woods Set
78   Lady Hailstorm Titanium Woods Set
87      Lady Hailstorm Steel Woods Set
121                     Husky Rope 200

Geef een overzicht met daarin per (achternaam van) medewerker of hij/zij manager is of niet, door deze informatie toe te voegen als extra 'Ja/Nee'-kolom.<br>
Hint: gebruik een for-loop waarin je o.a. bepaalt of het woord 'Manager' in de functie (position_en) staat. (2 kolommen, 102 rijen).

In [45]:
# Maak eerst even een kopie met alleen de benodigde kolommen (voorkomt foutmeldingen)
manager_df = sales_staff_df[['LAST_NAME', 'POSITION_EN']].copy()

# Loop door het DataFrame heen (zoals geleerd in de hoorcolleges)
for index, row in manager_df.iterrows():
    
    # Check of het woord 'Manager' in de functietitel zit
    if 'Manager' in str(row['POSITION_EN']):
        manager_df.at[index, 'Is Manager?'] = 'Ja'
    else:
        manager_df.at[index, 'Is Manager?'] = 'Nee'

# Selecteer de uiteindelijke 2 kolommen om te printen
resultaat_managers = manager_df[['LAST_NAME', 'Is Manager?']]

print(resultaat_managers)

     LAST_NAME Is Manager?
0         Pagé          Ja
1       Michel         Nee
2     Clermont         Nee
3       Jauvin         Nee
4    Wiesinger         Nee
..         ...         ...
97    Laermans         Nee
98     De Crée         Nee
99     Lattrez         Nee
100  Seefelder         Nee
101     Grüner         Nee

[102 rows x 2 columns]

Met de onderstaande code laat je Python het huidige jaar uitrekenen.

In [46]:
from datetime import date
date.today().year

2026

Met de onderstaande code selecteer je op een bepaald jaartal uit een datum.

In [47]:
from datetime import datetime

date_str = '16-8-2013'
date_format = '%d-%m-%Y'
date_obj = datetime.strptime(date_str, date_format)

date_obj.year

2013

Geef met behulp van bovenstaande hulpcode een overzicht met daarin op basis van het aantal jaar dat iemand in dienst is of een medewerker ‘kort in dienst’ (minder dan 30 jaar in dienst) of een ‘lang in dienst’ (groter dan gelijk aan 30 jaar in dienst) is. Geef daarbij per medewerker in een aparte kolom zowel ‘kort in dienst’ als ‘lang in dienst’ aan. Gebruik (wederom) een for-loop.<br>
(2 kolommen, 102 rijen)

In [48]:
from datetime import datetime, date

# 1. Haal het huidige jaar op (via de methode van de docent)
huidig_jaar = date.today().year

# Kopieer de kolommen die we nodig hebben
dienst_df = sales_staff_df[['LAST_NAME', 'DATE_HIRED']].copy()

# 2. Loop door de medewerkers heen
for index, row in dienst_df.iterrows():
    date_str = str(row['DATE_HIRED'])
    
    # Soms staan er tijdstippen achter de datum (zoals 00:00:00). We pakken de eerste 10 tekens.
    date_str_short = date_str[:10]
    
    # Omdat SQLite datums zowel in 'DD-MM-YYYY' als 'YYYY-MM-DD' opslaat,
    # doen we dit veilig via een 'try-except' om fouten te voorkomen:
    try:
        # Probeer het format van de hint van de docent
        date_obj = datetime.strptime(date_str_short, '%d-%m-%Y')
    except ValueError:
        # Werkt dat niet, gebruik dan deze (standaard voor databases)
        date_obj = datetime.strptime(date_str_short, '%Y-%m-%d')
        
    # 3. Reken de dienstjaren uit
    jaar_in_dienst = date_obj.year
    jaren_werkzaam = huidig_jaar - jaar_in_dienst
    
    # 4. Vul de nieuwe kolom in met de for-loop logic
    if jaren_werkzaam < 30:
        dienst_df.at[index, 'Dienstverband'] = 'kort in dienst'
    else:
        dienst_df.at[index, 'Dienstverband'] = 'lang in dienst'

# Print alleen de twee gevraagde kolommen
resultaat_dienst = dienst_df[['LAST_NAME', 'Dienstverband']]

print(resultaat_dienst)

     LAST_NAME   Dienstverband
0         Pagé  lang in dienst
1       Michel  lang in dienst
2     Clermont  kort in dienst
3       Jauvin  kort in dienst
4    Wiesinger  kort in dienst
..         ...             ...
97    Laermans  kort in dienst
98     De Crée  kort in dienst
99     Lattrez  kort in dienst
100  Seefelder  kort in dienst
101     Grüner  kort in dienst

[102 rows x 2 columns]